[phases.build]
cmds = [
    "chmod +x build.sh",
    "./build.sh"
]

[phases.start]
cmd = "python manage.py migrate --noinput && python init_railway.py && gunicorn dulceria_pos.wsgi --config gunicorn.conf.py"